### ISSUE TITLE
Rebuilt version with extra features

### ISSUE THREAD

**Issue by deathbybandaid** [dgw/sopel-duel#50]
over in `#spiceworks` on freenode, we really enjoyed playing your version of duels!

I've been teaching myself python, and I was inspired to rebuild this module from the ground up.

I thought you might want to take a look at what it has become!

My version includes a HUGE array of new features. Let me know what you think!

https://github.com/deathbybandaid/SpiceBot/blob/master/modules/Main/Duels.py

**Comment by dgw** [comment]
Note: I updated the URL in the OP because the file was renamed multiple times in the ~7,000 commit history of the SpiceBot repo. (And the repo itself was renamed.)

Interesting to glance at, I guess, but the rewrite is perhaps too specific to that particular bot instance for it to be useful to this project.
